on:
  release:
    types:
      - published
name: Deploy
jobs:
  deploy:
    runs-on: centos7-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with: # shimataro/ssh-key-actionに渡すパラメーター
          private-key: ${{ secrets.SSH_KEY }} # 必須
          public-key: ${{ secrets.SSH_KEY_PUBLIC }} # 必須
          name: id_rsa # 省略可
          known-hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
      - name: run deploy script
        run: bash deploy.sh
