version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: PROD
    env_file: ./.env.prod
    environment:
      NODE_ENV: production
    working_dir: /app
    volumes:
      - ./frontend:/app
    entrypoint: yarn build
  api:
    build:
      context: ./api
      target: PROD
    env_file:
      - ./.env.prod
      - ./.env.prod.secret
    environment:
      NODE_ENV: production
    working_dir: /src
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./api/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - ./api/src:/src
      - ./api/src/images:/images
      - /tmp/app:/tmp/app
    entrypoint: sh ./entrypoint.sh
    restart: always
  proxy:
    build: ./proxy
    ports:
      - 39999:80
    depends_on:
      - api
    volumes:
      - ./proxy/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/webbash
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env.prod
      - ./.env.prod.secret
    volumes:
      - ./mongo_db:/data/db
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./elastic/kibana.prod.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 35601:5601
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    entrypoint: >
      bash -c "chmod +x /tmp/install-plugin.sh &&
             /tmp/install-plugin.sh analysis-kuromoji &&
             /tmp/install-plugin.sh analysis-icu &&
             docker-entrypoint.sh"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elastic/install-plugin.sh:/tmp/install-plugin.sh
      - ./elastic/esdata01:/usr/share/elasticsearch/data
    ports:
      - 39200:9200

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
