version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 4040:8080
    tty: true
  backend:
    depends_on:
      - frontend
    build:
      context: ./backend
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./backend/src:/app
      - ./backend/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
    entrypoint: bash /app/entrypoint.dev.sh
    restart: always
  api:
    build:
      context: ./api
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./api/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - ./api/src:/app
      - /tmp/app:/tmp/app
      - ./images:/app/images
    ports:
      - 80
    entrypoint: bash /app/entrypoint.dev.sh
    restart: always
  proxy:
    build: ./proxy
    ports:
      - 5919:80
    depends_on:
      - backend
      - api
    volumes:
      - ./proxy/etc/nginx/conf.d/default:/etc/nginx/conf.d/default
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./elastic/kibana.dev.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    entrypoint: >
      bash -c "chmod +x /tmp/install-plugin.sh &&
             /tmp/install-plugin.sh analysis-kuromoji &&
             /tmp/install-plugin.sh analysis-icu &&
             docker-entrypoint.sh"
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elastic/install-plugin.sh:/tmp/install-plugin.sh
      - ./elastic/esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    entrypoint: >
      bash -c "chmod +x /tmp/install-plugin.sh &&
               /tmp/install-plugin.sh analysis-kuromoji &&
               /tmp/install-plugin.sh analysis-icu &&
               docker-entrypoint.sh"
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elastic/install-plugin.sh:/tmp/install-plugin.sh
      - ./elastic/esdata02:/usr/share/elasticsearch/data

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
