version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 4040:8080
    tty: true
  api:
    build:
      context: ./api
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /src
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./api/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - ./api/src:/src
      - ./api/src/images:/images
      - /tmp/app:/tmp/app
    ports:
      - 80
    entrypoint: sh ./entrypoint.dev.sh
    restart: always
  proxy:
    build: ./proxy
    ports:
      - 5919:80
    depends_on:
      - api
    volumes:
      - ./proxy/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mongo:
    image: mongo
    restart: always
    env_file: ./.env.dev
    volumes:
      - ./mongo_db:/data/db
