version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 4040:8080
    tty: true
  backend:
    depends_on:
      - frontend
    build:
      context: ./backend
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./backend/src:/app
    entrypoint: bash /app/entrypoint.dev.sh
  api:
    build:
      context: ./api
      target: DEV
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./api/src:/app
      - /tmp/app:/tmp/app
      - ./images:/app/images
    ports:
      - 80
    entrypoint: bash /app/entrypoint.dev.sh
  proxy:
    build: ./proxy
    ports:
      - 8080:80
    depends_on:
      - backend
      - api
