name: Test on Predeploy
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SSH Remove Previous Dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: "rm -rf ./test"
          use_insecure_cipher: true
      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: ${{ secrets.TEST_TARGET }}
          use_insecure_cipher: true
      - name: SSH Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ${{ secrets.TEST_SCRIPT }}
          use_insecure_cipher: true
      - name: Copy Coverage Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: "cp test/api/src/coverage.xml /var/www/myadmin"
          use_insecure_cipher: true
      - name: cUrl Coverage Files
        run: curl https://db.chomama.jp/coverage.xml -o coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: pytest-codecov
          fail_ci_if_error: true
