name: Test on Merge
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update Docker Compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0-rc4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose-3
      - name: CHMOD Docker Compose
        run: sudo chmod 777 /usr/local/bin/docker-compose-3
      - name: Add Secret Environment Variables
        run: ${{ secrets.SECRET_ENVVAR }}
      - name: Build Docker Images
        run: docker-compose-3 -f docker-compose.prod.yml build
      - name: Build Frontend
        run: docker-compose-3 -f docker-compose.prod.yml run --entrypoint "bash -c 'yarn install --production=false && yarn build'" frontend
      - name: Run Database
        run: docker-compose-3 -f docker-compose.prod.yml up -d es01 es02 mongo
      - name: OK! Wait 15 seconds
        run: sleep 15
      - name: Run Service
        run: docker-compose-3 -f docker-compose.prod.yml up -d api proxy
      - name: Run API Test
        run: docker-compose-3 -f docker-compose.prod.yml exec api pytest
